name: Docker in Docker
on:
    workflow_dispatch:

jobs:
    docker-info:
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
            options: --privileged
        steps:
            - name: Docker info
              run: docker info