name: Docker in Docker
on:
    workflow_dispatch:

jobs:
    docker-info:
        runs-on: self-hosted
        container:
            image: docker:stable
            options: --privileged
        steps:
            - name: Docker info
              run: docker info