on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    strategy:
      matrix: 
        name: ["Jordan", "Sarah", "Blake", "Chelsea", "Ashton"]
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: running
        run: sleep 3600s
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello name 
        run: echo "Hello ${{ matrix.name }}!"
#         uses: ./ # Uses an action in the root directory
#         id: hello
#         with:
#           who-to-greet: 'Mona the Octocat'
#       # Use the output from the `hello` step
#       - name: Get the output time
#         run: echo "The time was ${{ steps.hello.outputs.time }}"
